#include "tuple.h"

void ntuple::set_core_address()
{
    // Trigger
    evtch->SetBranchAddress("mip1_trigger", &mip1_trigger);
    evtch->SetBranchAddress("mip2_trigger", &mip2_trigger);
    evtch->SetBranchAddress("HET_trigger", &HET_trigger);
    evtch->SetBranchAddress("LET_trigger", &LET_trigger);
    evtch->SetBranchAddress("MIP_trigger", &MIP_trigger);
    evtch->SetBranchAddress("general_trigger", &general_trigger);
    // STK
    evtch->SetBranchAddress("STK_bestTrack_npoints", &STK_bestTrack_npoints);
    evtch->SetBranchAddress("STK_bestTrack_nholesX", &STK_bestTrack_nholesX);
    evtch->SetBranchAddress("STK_bestTrack_nholesY", &STK_bestTrack_nholesY);
    evtch->SetBranchAddress("STK_bestTrack_slopeX", &STK_bestTrack_slopeX);
    evtch->SetBranchAddress("STK_bestTrack_slopeY", &STK_bestTrack_slopeY);
    evtch->SetBranchAddress("STK_bestTrack_interceptX", &STK_bestTrack_interceptX);
    evtch->SetBranchAddress("STK_bestTrack_interceptY", &STK_bestTrack_interceptY);
    evtch->SetBranchAddress("STK_bestTrack_costheta", &STK_bestTrack_costheta);
    evtch->SetBranchAddress("STK_bestTrack_phi", &STK_bestTrack_phi);
    evtch->SetBranchAddress("STK_bestTrack_extr_BGO_topX", &STK_bestTrack_extr_BGO_topX);
    evtch->SetBranchAddress("STK_bestTrack_extr_BGO_topY", &STK_bestTrack_extr_BGO_topY);
    evtch->SetBranchAddress("STK_bestTrack_STK_BGO_topX_distance", &STK_bestTrack_STK_BGO_topX_distance);
    evtch->SetBranchAddress("STK_bestTrack_STK_BGO_topY_distance", &STK_bestTrack_STK_BGO_topY_distance);
    evtch->SetBranchAddress("STK_bestTrack_angular_distance_STK_BGO", &STK_bestTrack_angular_distance_STK_BGO);
    evtch->SetBranchAddress("STK_chargeX", &STK_chargeX);
    evtch->SetBranchAddress("STK_chargeY", &STK_chargeY);
    evtch->SetBranchAddress("STK_charge", &STK_charge);
    // BGO
    evtch->SetBranchAddress("energy", &energy);
    evtch->SetBranchAddress("energy_corr", &energy_corr);
    evtch->SetBranchAddress("eLayer", &eLayer);
    evtch->SetBranchAddress("BGOrec_slopeX", &BGOrec_slopeX);
    evtch->SetBranchAddress("BGOrec_slopeY", &BGOrec_slopeY);
    evtch->SetBranchAddress("BGOrec_interceptX", &BGOrec_interceptX);
    evtch->SetBranchAddress("BGOrec_interceptY", &BGOrec_interceptY);
    evtch->SetBranchAddress("sumRms", &sumRms);
    evtch->SetBranchAddress("rmsLayer", &rmsLayer);
    evtch->SetBranchAddress("fracLayer", &fracLayer);
    evtch->SetBranchAddress("fracLast", &fracLast);
    evtch->SetBranchAddress("fracLast_13", &fracLast_13);
    evtch->SetBranchAddress("lastBGOLayer", &lastBGOLayer);
    evtch->SetBranchAddress("nBGOentries", &nBGOentries);
    evtch->SetBranchAddress("energy_1R_radius", &energy_1R_radius);
    evtch->SetBranchAddress("energy_2R_radius", &energy_2R_radius);
    evtch->SetBranchAddress("energy_3R_radius", &energy_3R_radius);
    evtch->SetBranchAddress("energy_5R_radius", &energy_5R_radius);
    // PSD
    evtch->SetBranchAddress("PSD_chargeX", &PSD_chargeX);
    evtch->SetBranchAddress("PSD_chargeY", &PSD_chargeY);
    evtch->SetBranchAddress("PSD_charge", &PSD_charge);
    // NUD
    evtch->SetBranchAddress("NUD_ADC", &nud_adc);
    evtch->SetBranchAddress("NUD_total_ADC", &nud_total_adc);
    evtch->SetBranchAddress("NUD_max_ADC", &nud_max_adc);
    evtch->SetBranchAddress("NUD_max_channel_ID", &nud_max_channel_id);
    // Classifiers
    evtch->SetBranchAddress("xtr", &xtr);
    evtch->SetBranchAddress("xtrl", &xtrl);
    // Filters
    evtch->SetBranchAddress("evtfilter_out_energy_range", &evtfilter_out_energy_range);
    evtch->SetBranchAddress("evtfilter_evt_triggered", &evtfilter_evt_triggered);
    evtch->SetBranchAddress("evtfilter_correct_bgo_reco", &evtfilter_correct_bgo_reco);
    evtch->SetBranchAddress("evtfilter_good_event", &evtfilter_good_event);
    evtch->SetBranchAddress("evtfilter_geometric", &evtfilter_geometric);
    evtch->SetBranchAddress("evtfilter_BGO_fiducial", &evtfilter_BGO_fiducial);
    evtch->SetBranchAddress("evtfilter_BGO_fiducial_maxElayer_cut", &evtfilter_BGO_fiducial_maxElayer_cut);
    evtch->SetBranchAddress("evtfilter_BGO_fiducial_maxBarLayer_cut", &evtfilter_BGO_fiducial_maxBarLayer_cut);
    evtch->SetBranchAddress("evtfilter_BGO_fiducial_BGOTrackContainment_cut", &evtfilter_BGO_fiducial_BGOTrackContainment_cut);
    evtch->SetBranchAddress("evtfilter_nBarLayer13_cut", &evtfilter_nBarLayer13_cut);
    evtch->SetBranchAddress("evtfilter_maxRms_cut", &evtfilter_maxRms_cut);
    evtch->SetBranchAddress("evtfilter_track_selection_cut", &evtfilter_track_selection_cut);
    evtch->SetBranchAddress("evtfilter_psd_stk_match_cut", &evtfilter_psd_stk_match_cut);
    evtch->SetBranchAddress("evtfilter_psd_charge_cut", &evtfilter_psd_charge_cut);
    evtch->SetBranchAddress("evtfilter_stk_charge_cut", &evtfilter_stk_charge_cut);
    evtch->SetBranchAddress("evtfilter_psd_charge_measurement", &evtfilter_psd_charge_measurement);
    evtch->SetBranchAddress("evtfilter_stk_charge_measurement", &evtfilter_stk_charge_measurement);
    evtch->SetBranchAddress("evtfilter_xtrl_tight_cut", &evtfilter_xtrl_tight_cut);
    evtch->SetBranchAddress("evtfilter_xtrl_loose_cut", &evtfilter_xtrl_loose_cut);
    evtch->SetBranchAddress("evtfilter_all_cut", &evtfilter_all_cut);
    evtch->SetBranchAddress("cut_nBarLayer13", &cut_nBarLayer13);
    evtch->SetBranchAddress("cut_maxRms", &cut_maxRms);
    evtch->SetBranchAddress("cut_track_selection", &cut_track_selection);
    evtch->SetBranchAddress("cut_psd_stk_match", &cut_psd_stk_match);
    evtch->SetBranchAddress("cut_psd_charge", &cut_psd_charge);
    evtch->SetBranchAddress("cut_stk_charge", &cut_stk_charge);
    evtch->SetBranchAddress("nActiveCuts", &nActiveCuts);
}