name: C/C++ building test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: linkingROOT
      run: source deps/ROOT/Ubuntu/root/bin/thisroot.sh
    - name: building
      run: make rebuild
    - name: cleaning
      run: make clean_all
