name: CentOS - DAMPE framework

on: [push]

jobs:
  dampeFrame:
    runs-on: ubuntu-latest
    name: DAMPE Framework Building Test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: remote building
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PROXY_KEY }}
  +     proxy_host: ${{ secrets.PROXY_HOST }}
  +     proxy_username: ${{ secrets.PROXY_USERNAME }}
  +     proxy_key: ${{ secrets.PROXY_KEY }}
  +     proxy_port: ${{ secrets.PROXY_PORT }}
        script: whoami
