name: CentOS - DAMPE framework

on: [push]

jobs:
  dampeFrame:
    runs-on: ubuntu-latest
    name: DAMPE Framework Building Test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: remote building
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
