name: CentOS - DAMPE framework

on: [push]

jobs:
  dampeFrame:
    runs-on: ubuntu-latest
    name: DAMPE Framework Building Test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: remote building
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: 'pi@ecatanzani.ddns.net:23785'
        privateKey: ${{ secrets.KEY }}
        command: ls -lah
