on: [push]

jobs:
  dampeFrame:
    runs-on: ubuntu-latest
    name: DAMPE Framework Building Test
    steps:
    - name: building
      uses: ecatanzani/DAMPE_builder
    - name: action steps
      uses: ./